// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nomina_Empleados_Leng.DAL;

namespace Nomina_Empleados_Leng.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220302125118_Migracion Inicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Nomina_Empleados_Leng.Entidades.Empleados", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Telefono")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmpleadoId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Nomina_Empleados_Leng.Entidades.Nominas", b =>
                {
                    b.Property<int>("NominaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AFP")
                        .HasColumnType("REAL");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("HorasExtra")
                        .HasColumnType("REAL");

                    b.Property<double>("ISR")
                        .HasColumnType("REAL");

                    b.Property<double>("SFS")
                        .HasColumnType("REAL");

                    b.Property<double>("SalarioMensual")
                        .HasColumnType("REAL");

                    b.Property<double>("SueldoTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalDecuentos")
                        .HasColumnType("REAL");

                    b.HasKey("NominaId");

                    b.ToTable("Nominas");
                });
#pragma warning restore 612, 618
        }
    }
}
